services:
  exedb:
    env_file:
      - .env
    container_name: exedb
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA}
      - SA_PASSWORD=${SA_PASSWORD}
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_exedb:/var/opt/mssql

  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"
