global using Asp.Versioning.Builder;
global using MediatR;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Http;
global using exe_backend.Contract.Shared;
global using Microsoft.AspNetCore.Mvc;
global using exe_backend.Contract.Common.Enums;
global using System.Security.Claims;
global using exe_backend.Contract.Common.Constants;
