name: Build and deploy ASP.Net Core app to Azure Web App - exewebapi

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      # Kiểm tra thư mục làm việc hiện tại
      - name: Print current directory
        run: pwd

      # Liệt kê các tệp và thư mục để kiểm tra tệp .sln
      - name: List files to check structure
        run: ls -R

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Thay đổi thư mục làm việc để trỏ đến thư mục chứa tệp .sln
      - name: Change directory to the folder containing the .sln
        run: cd src/exe_backend.Api

      # Xây dựng và xuất bản ứng dụng
      - name: Build with dotnet
        run: dotnet build exe_backend.Api.sln --configuration Release

      - name: dotnet publish
        run: dotnet publish exe_backend.Api.sln -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'exewebapi'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CC01386D64D04782AFDAC247ACF176FA }}
